MODEL:
  NUM_CLASSES: 21
  BACKBONE:
    NAME: 'resnet18'
    OUT_CHANNELS: (64, 128, 256, 512, 1024)
  PRIORS:
    FEATURE_MAPS: [56, 28, 14, 7, 1]
    STRIDES: [24, 48, 75, 112, 224]
    MIN_SIZES: [50, 90, 130, 170, 210]
    MAX_SIZES: [90, 130, 170, 210, 250]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 224
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/resnet18_ssd300_voc0712'